export const listings = [
  {
    id: 1,
    slug: "modern-student-room",
    title: "Modern Student Room",
    university: "Africa University",
    suburb: "Fairbridge Park",
    city: "Mutare",
    roomType: "Private Room",
    price: 180,
    image: "/images/listings/room2.png",
    amenities: ["Solar", "Borehole", "Wi-Fi"],
    featured: true,
    verified: true,
  },

  {
    id: 2,
    slug: "shared-apartment-chikanga",
    title: "Shared Apartment",
    university: "Africa University",
    suburb: "Chikanga",
    city: "Mutare",
    roomType: "Shared Room",
    price: 120,
    image: "/images/listings/room3.png",
    amenities: ["Borehole", "Wi-Fi"],
    featured: true,
    verified: true,
  },

  {
    id: 3,
    slug: "private-room-near-msuas",
    title: "Private Room",
    university: "MSUAS",
    suburb: "Fernhill",
    city: "Mutare",
    roomType: "Private Room",
    price: 150,
    image: "/images/listings/room3.png",
    amenities: ["Solar", "Wi-Fi"],
    featured: true,
    verified: true,
  },

  {
    id: 4,
    slug: "student-apartment-uz",
    title: "Student Apartment",
    university: "University of Zimbabwe",
    suburb: "Avondale",
    city: "Harare",
    roomType: "Apartment",
    price: 220,
    image: "/images/listings/room1.png",
    amenities: ["Solar", "Borehole", "Wi-Fi"],
    featured: false,
    verified: true,
  },

  {
    id: 5,
    slug: "budget-shared-room-nust",
    title: "Budget Shared Room",
    university: "NUST",
    suburb: "Ascot",
    city: "Bulawayo",
    roomType: "Shared Room",
    price: 90,
    image: "/images/listings/room2.png",
    amenities: ["Wi-Fi"],
    featured: false,
    verified: true,
  },

  {
    id: 6,
    slug: "modern-flat-uz",
    title: "Modern Flat",
    university: "Africa University",
    suburb: "Murambi",
    city: "Mutare",
    roomType: "Shared Room",
    price: 200,
    image: "/images/listings/room3.png",
    amenities: ["Solar", "Borehole", "Wi-Fi"],
    featured: true,
    verified: true,
  }
];