export const listings = [
  {
    id: 1,
    title: "Modern Student Room",
    university: "Africa University",
    city: "Fairbridge Park, Mutare",
    price: 180,
    image: "/images/listings/room1.png",
    verified: true,
    solar: true,
    WaterSupply: true,
    wifi: true,
  },
  {
    id: 2,
    title: "Private Room Near MSUAS",
    university: "MSUAS",
    city: "Fernhill, Mutare",
    price: 150,
    image: "/images/listings/room2.png",
    verified: true,
    solar: true,
    WaterSupply: true,
    wifi: true,
  },
  {
    id: 3,
    title: "Shared Apartment",
    university: "Africa University",
    city: "Chikanga, Mutare",
    price: 120,
    image: "/images/listings/room3.png",
    verified: true,
    solar: true,
    WaterSupply: true,
    wifi: true,
  },
];